### ISSUE TITLE
Enable/Disable Sample Velocity Tracking (selected sample, and all samples in instruments)

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#43]
as requested by @icasiino

- [x] Enable Sampler Velocity Tracking
- [x] Disabled Sampler Velocity Tracking
- [x] Enable Sampler Velocity Tracking ALL
- [x] Disabled Sampler Velocity Tracking ALL

what i don't know is if this even exists in the API.

**Comment by esaruoho** [comment]
<img width="336" alt="Screenshot 2024-05-04 at 17 00 32" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/7dacf055-9396-4002-bb46-bbd492d0f2cd">

<img width="338" alt="Screenshot 2024-05-04 at 17 00 59" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/66a78888-c094-4f00-b50d-6505b7ab8d9d">

**Comment by esaruoho** [comment]
yep. this is ready and will wait for the next (larger) release. closing for now.

**Comment by icasiino** [comment]
Excelente!¡
